name: Get Subscription Weekly

on:
  schedule:
    - cron: "0 16 * * 6"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pyyaml requests
          [ -f aggregate/requirements.txt ] && pip install -r aggregate/requirements.txt

      - name: Collect Subscribe
        id: collect
        working-directory: aggregate
        run: python -u subscribe/collect.py

      - name: Validate generated files
        working-directory: aggregate
        run: |
          ls -l proxies.yaml subscribes.txt domains.txt valid-domains.txt
          [ -f proxies.yaml ] || exit 1

      - name: Update Gist
        working-directory: aggregate
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh gist edit ${{ secrets.GIST_ID }} \
            --add proxies.yaml \
            --add subscribes.txt \
            --add domains.txt \
            --add valid-domains.txt
