name: Get Subscription Weekly

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Debug check
        run: |
          echo "PAT exists: ${{ toJson(secrets.PAT) != '' }}"  # 输出true/false
          echo "GIST_ID: ${{ secrets.GIST_ID }}"
          mkdir data
          cd data && touch subscribes.txt
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.PAT }}
          gist_id: ${{ secrets.GIST_ID }}
          file_path: data/subscribes.txt
          file_type: binary          
