name: Get Subscription Weekly

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Debug check
        run: |
          echo "PAT exists: ${{ toJson(secrets.PAT) != '' }}"  # 输出true/false
          echo "GIST_ID: ${{ secrets.GIST_ID }}"
          # 注意：实际Secret值会被GitHub自动隐藏
      - name: Update Gist
        working-directory: data
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh gist edit ${{ secrets.GIST_ID }} \
            --add subscribes.txt
