name: Get Subscription Weekly

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pyyaml requests && pip install -r requirements.txt

      - name: Collect Subscribe
        id: collect
        run: python -u subscribe/collect.py

      - name: Merge and Convert Subscriptions
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          python -u subscribe/merge_and_convert.py \
            --gist-id ${{ secrets.GIST_ID }} \
            --token ${{ secrets.PAT }} \
            --filename subscribes.txt \
            --hours 6 \
            --output merged_subscribes.txt

      - name: Execute Python Script
        working-directory: extra-sub
        run: |
          python -u main.py \
            --gist-id ${{ secrets.GIST_ID }} \
            --token ${{ secrets.PAT }}        


          
